server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-service
    username: root
    password: rootpass
    drive-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka